name: Convert

on:
  workflow_dispatch:
    inputs:
      xlsFile:
        description: 'XLS file with test data'
        required: true
      branch:
        description: 'Branch to commit updated files'
        default: 'new-data'

jobs:
  LoadNewCSV:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - run: |
        cd /tmp &&\
        wget https://github.com/hl7au/au-fhir-test-data-utils/releases/latest/download/xls-converter.zip &&\
        unzip xls-converter.zip &&\
        pip install xls_converter* &&\
        rm -rf xls_converter* xls-converter.zip
    - run: python -m xls_converter.main ${{ github.event.inputs.xlsFile }} testdata-csv
    - name: Install deps
      uses: ./.github/deps
    - name: Convert to json
      uses: ./.github/fhirmapping
    - name: Create Pull Request
      id: create-pull-request
      uses: peter-evans/create-pull-request@v6
      with:
          token: ${{ secrets.GITHUB_TOKEN  }}
          delete-branch: true
          commit-message: Update test data
          title: Update test data
          body: New updates from ${{ github.event.inputs.xlsFile }}
          labels: automated-pr
          base: master
          branch: ${{ github.event.inputs.branch }}
    - name: Report
      uses: ./.github/report
      with:
        issue: ${{ steps.create-pull-request.outputs.pull-request-number }}
