name: Run Validator
run-name: ${{ github.actor }} is generating FHIR resources ğŸ”¥
on: [push]
jobs:
  Install-And-Run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - name: Cache apt-install
      # You may pin to the exact commit or the version.
      # uses: daaku/gh-action-apt-install@92eea4f84f90c895b544aaec6ae21839127c84e5
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
         # Packages to install.
         packages:
           libicu-dev 
         execute_install_scripts: true
      - run: |
         mkdir generated
         pushd .
         cd linux
         chmod +x GenerateAll.sh
         ./GenerateAll.sh
         popd
      - name: Archive generated results results
        uses: actions/upload-artifact@v4
        with:
          name: generated-resources
          path: generated