name: Run Validator
run-name: ${{ github.actor }} is validating FHIR resources ðŸ”¥
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ðŸ This job's status is ${{ job.status }}."
      - name: Cache apt-install
      # You may pin to the exact commit or the version.
      # uses: daaku/gh-action-apt-install@92eea4f84f90c895b544aaec6ae21839127c84e5
        uses: daaku/gh-action-apt-install@v4
        with:
         # Packages to install.
         packages:
           wget
           default-jdk
           xsltproc
      - run: xsltproc extract_error_files.xsl m_validation.xml > quarantine_errors.sh
      - run: chmod +x quarantine_errors.sh
      - run: ./quarantine_errors.sh
      - run: java -jar validator_cli.jar mixed/*.json -version 4.0.1 -tx https://tx.dev.hl7.org.au/fhir -ig hl7.fhir.au.core#0.4.0-preview  -sct au -level errors -jurisdiction au -html-output m_validation.html -output m_validation.xml
