name: Run FHIR Resource Upload Tool
run-name: ${{ github.actor }} is generating FHIR resources ğŸ”¥
on: [push]
jobs:
  Install-And-Run:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      hapi:
        # Docker Hub image
        image: smartonfhir/hapi-5:r4-synthea
        ports:
          - 8080
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - name: Generate resources
      # You may pin to the exact commit or the version.
      # uses: daaku/gh-action-apt-install@92eea4f84f90c895b544aaec6ae21839127c84e5
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
         # Packages to install.
         packages:
           libicu-dev 
         execute_install_scripts: true
      - run: |
         export CREDENTIALS=`echo ${FHIR_USER_ID}:${FHIR_USER_PASSWORD} | base64`
         cd linux
         chmod +x UploadAll.sh
         ./UploadAll.sh
         ./compiledUploadScript.sh http://localhost:${{ job.services.hapi.ports['8080'] }} # ${TARGET_FHIR_SERVER} ${CREDENTIALS}